---
title: "Project Management and Reproducibility in RStudio"
author: "Doug Joubert"
date: '2022-07-01'
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

This one-hour class focuses on data and project management
using R and RStudio. RStudio makes it possible to work on a complete research
project in a more efficient, integrated, and organized manner. RStudio also
connects with Git and Github and learners will have a chance to experiment with
this integration and understand its advantages for collaboration and version
control. Participants will learn how to create reproducible documents that
combine code, analysis, and narrative. This intermediate-level course is
designed to be relevant to students from different disciplines. Some
familiarity or experience in R and RStudio is recommended but not required. Students
are encouraged to install [R](https://mirrors.nics.utk.edu/cran/) and [RStudio](https://www.rstudio.com/products/rstudio/download/#download) before
the webinar so that they can follow along with the instructor. Attendees will
need to download the class data before the webinar.

Upon completion of this class students should be able to:

* Discuss best practices for organizing data in an RStudio project
* Define the term tidy data and its role in reproducibility
* List the recommendations for tidy data
* Discuss the importance of using a data dictionary and read me files
* Ensure that their data is machine readable
* Create a new R project using a GitHub repository
* Distinguish between pulling and pushing data from a repository
* Create an R-markdown document
* Create a bibliography and link it to a R-markdown document

# Open Science

Licenses

**Licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) 2022 by [the authors](https://carpentries-incubator.github.io/Reproducible-Publications-with-RStudio/CITATION).**
