---
title: "R Class Descriptions (Advanced) with Learning Objectives (OCT 2023)"
author: "Doug Joubert"
date: "`r Sys.Date()`"
format: docx
editor: visual
echo: fenced
toc: true
toc-location: right
---

# Project Management in RStudio

## Description

This class focuses on data and project management using R and RStudio. RStudio makes it possible to work on a complete research project in a more efficient, integrated, and organized manner. This course is designed to be relevant to students from different disciplines.

Upon completion of this class students should be able to define project management from a data science perspective, list the advantages of using RStudio projects, apply best practices for setting up RStudio for projects, create a new RStudio Project, and discuss best practices for organizing data in an RStudio project

## Assumptions for This Class

This class makes a few assumptions about your understanding of R and RStudio. First, it assumed that you have already installed [R](https://cran.r-project.org/) and [RStudio](https://www.rstudio.com/products/RStudio/#Desktop). Second, is that you have experience with R. If not, here are some resources for getting started:

-   NIH Library [Introduction to R and RStudio](https://www.nihlibrary.nih.gov/training/introduction-r-and-rstudio-9)

-   [A (very) short introduction to R](https://cran.r-project.org/doc/contrib/Torfs+Brauer-Short-R-Intro.pdf)

-   [Quick-R](http://www.statmethods.net/)

-   [Getting up to speed with R](https://rkabacoff.github.io/datavis/Rintro.pdf)

# Version Control and GitHub (New)

## Description

This class introduces version control and using [GitHub](https://github.com/) for project versioning. Students will have a better understanding of version control and its advantages for collaboration and version control.

Upon completion of this class students should be able to, recognize why version control is useful, discuss the difference between Git and GitHub, list the options for authenticating to GitHub, and create a personal access token (PAT)

## Assumptions for This Class

This class makes a few assumptions about your understanding of R and RStudio:

1.  You have already installed [R](https://cran.r-project.org/) and [RStudio](https://www.rstudio.com/products/RStudio/#Desktop).
2.  You have experience with R. If not, here are some resources for getting started:

-   NIH Library [Introduction to R and RStudio](https://www.nihlibrary.nih.gov/training/introduction-r-and-rstudio-9) class
-   [A (very) short introduction to R](https://cran.r-project.org/doc/contrib/Torfs+Brauer-Short-R-Intro.pdf)
-   [Quick-R](http://www.statmethods.net/)
-   [Getting up to speed with R](https://rkabacoff.github.io/datavis/Rintro.pdf)

3.  You have already created a GitHub account

# Git in RStudio (Modified)

## Description

This class focuses on using Git and [GitHub](https://github.com/), with RStudio. Using integrated RStudio tools learners will have a chance to experiment with this integration and understand its advantages for collaboration and version control. Students need to install [R](https://mirrors.nics.utk.edu/cran/) and the current version of [RStudio](https://www.rstudio.com/products/rstudio/download/#download) before the class so that they can follow along with the instructor.

Upon completion of this class students should be able to discuss the difference between Git and GitHub, list the options for authenticating to GitHub, create a new R project using a GitHub repository, and distinguish between pulling and pushing data from a repository

## Assumptions for This Class

This class makes a few assumptions about your understanding of R and RStudio:

1.  You have already installed [R](https://cran.r-project.org/) and [RStudio](https://www.rstudio.com/products/RStudio/#Desktop).
2.  You have experience with R. If not, here are some resources for getting started:

-   NIH Library [Introduction to R and RStudio](https://www.nihlibrary.nih.gov/training/introduction-r-and-rstudio-9) class
-   [A (very) short introduction to R](https://cran.r-project.org/doc/contrib/Torfs+Brauer-Short-R-Intro.pdf)
-   [Quick-R](http://www.statmethods.net/)
-   [Getting up to speed with R](https://rkabacoff.github.io/datavis/Rintro.pdf)

3.  You have already created a GitHub account
4.  You have downloaded, installed, and verified Git on your computer
5.  You have taken the Version Control and GitHub class

# Introduction to Quarto for Scholarly Publishing (Revised)

## Description

This class is designed for those who want to extend the basics of R Markdown and apply those skills in [Quarto](https://quarto.org/). Quarto is an open-source scientific and technical publishing system that offers multilingual programming language support to create dynamic and static documents, books, presentations, blogs, and other online resources.

In this class you will learn about the similarities and differences between R-markdown and Quarto. You will also learn how to use Quarto to render documents in multiple formats, with a focus on scholarly publishing. Some familiarity or experience in R and RStudio is required. Upon completion of this class students should be able to distinguish between R-markdown and Quarto, identify publishing workflows using markdown, demonstrated the difference between the visual and source editors, create basic markdown elements, learn how to create and run code-blocks, and render a markdown document

## Assumptions for This Class

This class makes a few assumptions about your understanding of R and RStudio. First, it assumed that you have already installed [R](https://cran.r-project.org/) and [RStudio](https://www.rstudio.com/products/RStudio/#Desktop). Second, is that you have experience with R. If not, here are some resources for getting started:

-   NIH Library [Introduction to R and RStudio](https://www.nihlibrary.nih.gov/training/introduction-r-and-rstudio-9)

-   [A (very) short introduction to R](https://cran.r-project.org/doc/contrib/Torfs+Brauer-Short-R-Intro.pdf)

-   [Quick-R](http://www.statmethods.net/)

-   [Getting up to speed with R](https://rkabacoff.github.io/datavis/Rintro.pdf)

Third, is experience working in RStudio and creating scripts and/or markdown files.

# Quarto for Scholarly Publishing: Advanced Formatting (Revised)

## Description

This class is designed for those who want to extend the basics covered in the Introduction to Quarto for Scholarly Publishing class. In this class you will learn how to format tables, customize code blocks, and work with images. You must have taken Introduction to Quarto for Scholarly Publishing to be successful in this class.

Upon completion of this class students should be able to create tables, customize code-blocks, insert images into a markdown document and modify attributes, create document templates, and render a markdown document in multiple formats

## Assumptions for This Class

This class makes a few assumptions about your understanding of R and RStudio. First, it assumed that you have already installed [R](https://cran.r-project.org/) and [RStudio](https://www.rstudio.com/products/RStudio/#Desktop). Second, is that you have experience with R. If not, here are some resources for getting started:

-   NIH Library [Introduction to R and RStudio](https://www.nihlibrary.nih.gov/training/introduction-r-and-rstudio-9)

-   [A (very) short introduction to R](https://cran.r-project.org/doc/contrib/Torfs+Brauer-Short-R-Intro.pdf)

-   [Quick-R](http://www.statmethods.net/)

-   [Getting up to speed with R](https://rkabacoff.github.io/datavis/Rintro.pdf)

Third, you have taken the Introduction to Quarto for Scholarly Publishing class.

# Quarto for Scholarly Publishing: Working with Citations (Revised)

## Description

This class is designed for those who want to extend the basics covered in the [Reproducibility in RStudio: Basic Markdown](https://www.nihlibrary.nih.gov/training/reproducibility-rstudio-basic-markdown) class. This class uses [Quarto](https://quarto.org/) to render format citations and bibliographies using [Zotero](https://www.zotero.org/). [Zotero](https://www.zotero.org/) is a free, easy-to-use tool to help you collect, organize, annotate, cite, and share research. You must have taken Introduction to Quarto for Scholarly Publishing to be successful in this class.

Upon completion of this class students should be able to download and install Zotero, link RStudio to Zotero, create a bibliography and link it to a markdown document, insert citations using RStudio Visual Interface, and via the command line, and download and link a `CSL` file which specifies the formatting to use when generating the citations and bibliography

## Assumptions for This Class

This class makes a few assumptions about your understanding of R and RStudio. First, it assumed that you have already installed [R](https://cran.r-project.org/) and [RStudio](https://www.rstudio.com/products/RStudio/#Desktop). Second, is that you have experience with R. If not, here are some resources for getting started:

-   NIH Library [Introduction to R and RStudio](https://www.nihlibrary.nih.gov/training/introduction-r-and-rstudio-9)

-   [A (very) short introduction to R](https://cran.r-project.org/doc/contrib/Torfs+Brauer-Short-R-Intro.pdf)

-   [Quick-R](http://www.statmethods.net/)

-   [Getting up to speed with R](https://rkabacoff.github.io/datavis/Rintro.pdf)

Third, you have taken the Introduction to Quarto for Scholarly Publishing class.
