---
title: "R and RStudio Resources"
author: "Doug Joubert"
date: "`r Sys.Date()`"
editor: visual
format: docx
toc: true
toc-location: body
toc-title: Table of Contents
---

# Git and GitHub

## Happy Git and GitHub for the useR

[Happy Git and GitHub for the useR](https://happygitwithr.com/index.html): Wonderful resources if you new to git and GitHub. Happy Git provides opinionated instructions on how to:

-   Install Git and get it working smoothly with GitHub, in the shell and in the [RStudio IDE](https://www.rstudio.com/products/rstudio/).

-   Develop a few key workflows that cover your most common tasks.

-   Integrate Git and GitHub into your daily work with R and [R Markdown](https://rmarkdown.rstudio.com/).

# ggplot

# Markdown

## Academic Writing Using Markdown

A short guide to using markdown in [academic writing](https://bcrf.biochem.wisc.edu/2021/06/10/do-yourself-a-favor-learn-markdown-episode-3/).

## Brief History of R Markdown

2021 [presentation](https://slides.yihui.org/2021-Brazilian-R-Day.html) by Yihui Xie

## Polishing Documents

Presentation by Andrew Bray from his [RMD to Quarto workshop](https://rstudio-conf-2022.github.io/rmd-to-quarto/materials/2-polishing-documents/) section of the has some great information.

## R4DS Communicating with R Markdown (Quarto)

R4DS has a set of 3 chapter on Quarto, which are part of the updated [Communication section](https://r4ds.hadley.nz/communicate.html). The chapters focus on Quarto, other publishing frameworks, and an introduction to the "lab notebook" framework. Given that this content is part of the work-in-progress second edition of R for Data Science, you might want to consult the complete [first edition](https://r4ds.had.co.nz)

## R Markdown: The Definitive Guide

[online version](https://bookdown.org/yihui/rmarkdown/) of the printed book.

## R Markdown: Cookbood

[online version](https://bookdown.org/yihui/rmarkdown-cookbook/) of the printed book.

## R Markdown Cheat Sheets

RStudio has created a large number of cheat sheets, including the one-page R Markdown [cheat sheet](https://github.com/rstudio/cheatsheets/raw/main/rmarkdown-2.0.pdf). Also, contains contributed cheat sheets.

## R Markdown for Scientists

Book on r markdown, [aimed for scientists](https://rmd4sci.njtierney.com/). It was initially developed as a 3 hour workshop.

## Scientific Writing with Markdown

Great guide (with videos) on getting started with [markdown](https://jaantollander.com/post/scientific-writing-with-markdown/). He also covers tools other than RStudio.

# Project Management

## Managing Open and Reproducible Computational Projects

The [Managing Open and Reproducible Computational Projects](https://carpentries-incubator.github.io/managing-computational-projects/index.html) training material covers best practices for managing computational projects using data science methods. These lessons will help you design projects that are reproducible, transparent, and support collaboration. This training material is developed under the **Data Science for Biomedical Scientists** project. It massively reuses [The Turing Way](https://the-turing-way.netlify.app/) chapters and builds on [The Carpentries](https://carpentries.org/) and [Open Life Science](https://openlifesci.org/) practices.

## Using RStudio Projects

[Using RStudio Projects](https://support.posit.co/hc/en-us/articles/200526207-Using-RStudio-Projects)

# Publishing

## Getting started with GitHub Pages

Helps you set up a basic [GitHub Pages](https://docs.github.com/en/pages/getting-started-with-github-pages) site for yourself, your organization, or your project.

# Quarto

## Official Documentation & Quick Start Guides

### Official Quarto Documentation

Comprehensive [guides](https://quarto.org/docs/guide/) to using Quarto. If you are just starting out, you may want to explore the tutorials to learn the basics

### Hello, Quarto

In this [tutorial](https://quarto.org/docs/get-started/hello/rstudio.html) we'll show you how to use RStudio with Quarto. You'll edit code and markdown in RStudio just as you would with any computational document (e.g. R Markdown), and preview the rendered document in the Viewer tab as you work.

### Computations Tutorial

Quarto supports executable code blocks within markdown. This allows you to create fully reproducible documents and reports---the code required to produce your output is part of the document itself, and is automatically re-run whenever the document is rendered.

In this tutorial we'll show you how to author fully reproducible [computational documents](https://quarto.org/docs/get-started/computations) with Quarto in RStudio

### Authoring Tutorial

Tutorial discusses the various document [formats](https://quarto.org/docs/get-started/authoring/) you can produce with the same source code and show you how to add components like table of contents, equations, citations, etc. The visual markdown editor in RStudio makes many of these tasks easier so we'll highlight its use in this tutorial, but note that it's possible to accomplish these tasks in the source editor as well

## Tutorials and Workshops

### Reproducible Authoring with Quarto

2022 Toronto [Workshop on Reproducibility](https://www.youtube.com/watch?v=6p4vOKS6Xls) with Mine Çetinkaya-Rundel, with slides available on [GitHub](https://mine-cetinkaya-rundel.github.io/2022-repro-toronto)

### Making shareable documents with Quarto

Tutorial that will help you create a [website](https://openscapes.github.io/quarto-website-tutorial/) using Quarto, that auto-updates with GitHub.

### Getting started with Quarto

2022 [workshop](https://rstudio-conf-2022.github.io/get-started-quarto/) on getting started with Quarto, from Tom Moch. This 2-day workshop was designed for those who have no or little prior experience with R Markdown and who want to learn Quarto

### From R Markdown to Quarto

A [workshop](https://rstudio-conf-2022.github.io/rmd-to-quarto/) designed for those who want to take their R Markdown skills and expertise and apply them in Quarto, the next generation of R Markdown.

### List of Quarto Workshops and Resources

Maintained by [Mickaël Canouil](https://github.com/mcanouil), a curated [list](https://github.com/mcanouil/awesome-quarto#official-documentation--quickstarts) of [Quarto®](https://quarto.org/) docs, talks, tools, examples & articles the internet has to offer.

# Reproducibility

## Introduction to Reproducible Publications with RStudio

Lesson from the Carpentries, where participants will build on their research and analytical skills with R Studio by learning how to create [reproducible documents](https://carpentries-incubator.github.io/Reproducible-Publications-with-RStudio/) that combine code, analysis and narrative.

## R for Reproducible Scientific Analysis: Producing Reports With knitr

Learn how to recognise and compile the basic components of an [R Markdown](https://swcarpentry.github.io/r-novice-gapminder/15-knitr-markdown.html) file. Also, become familiar with R code chunks, and understand their purpose, structure and options

## Reproducible Research Data and Project Management in R

Course from Dr. Anna Krystalli that focuses on data and [project management through R](https://annakrystalli.me/rrresearchACCE20/) and Rstudio, will introduce students to best practice and equip them with modern tools and techniques for managing data and computational workflows to their full potential.

# R and RStudio

## Using the RStudio Terminal in the RStudio IDE

The RStudio [terminal](https://support.posit.co/hc/en-us/articles/115010737148-Using-the-RStudio-Terminal-in-the-RStudio-IDE) provides access to the system shell from within the RStudio IDE. It supports full-screen terminal applications such as vim, Emacs, and tmux as, well as regular command-line operations with line-editing and shell history

## Command Line Essentials

A short primer on how to navigate through a file structure at the [command line](https://datacarpentry.org/shell-genomics/02-the-filesystem/index.htm)l, from the [Introduction to the Command Line for Genomics Workshop](https://datacarpentry.org/shell-genomics/)

## Introduction to Data Analysis with R and Bioconductor: **R and RStudio**

Part of a larger (alpha stage) Carpentries workshop focused on data analysis with R and Bioconductor. This particular lesson describe the purpose of the RStudio Script, Console, Environment, and Plots panes. It also provides recommendations for organizing files and directories for a set of analyses as an R project, and understand the purpose of the working directory.

## R for Data Science (2e)

I used the website version (because it is free). This book will teach you how to do data science with R: You'll learn how to get your data into R, get it into the most useful structure, transform it and visualize it. In particular, the workflows [chapter](https://r4ds.hadley.nz/workflow-scripts.html) is really useful.

# Licenses

Licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) 2022 by [the authors](https://carpentries-incubator.github.io/Reproducible-Publications-with-RStudio/CITATION).
